spring:
  session:
    jdbc:
      initialize-schema: always
    timeout:
      seconds: '600'
    store-type: jdbc
  profiles:
    active: dev
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false
      FAIL_ON_SELF_REFERENCES: false
    deserialization:
      unwrap-root-value: false

server:
  error:
    include-message: always
    include-binding-errors: always
  port: 8081

logging:
  level:
    root : INFO
    dev : INFO
    org:
      springframework:
        web: INFO
        boot:
          autoconfigure: INFO
      hibernate : ERROR
debug: false

